on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json

      - run: npm install

      - run: npm run lint:prettier
      - run: npm run lint:tsc
      - run: npm run test

      - run: npx jsr publish
